activemq:
  brokerUrl: tcp://10.1.2.10:61616
  sessionCacheSize: 10
  cacheConsumers: false
  requestQueue: queue.request

filter:
  expression: payload.contains('test')

spring:
  kafka:
    producer:
      bootstrap-servers: 10.1.2.10:9092
      batch-size: 16384
      buffer-memory: 33554432
      retries: 0
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer